# Generated by Django 6.0.6 on 2026-06-09 17:20

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_alter_providerprofile_rating_rating'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rating',
            new_name='Review',
        ),
    ]
