# Generated by Django 6.0.6 on 2026-06-17 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_servicerequest_latitude_servicerequest_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='service_request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='services.servicerequest'),
        ),
    ]
