# Generated by Django 6.0.6 on 2026-06-17 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_alter_review_service_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providerprofile',
            name='rating',
            field=models.FloatField(default=0),
        ),
    ]
