# Generated by Django 6.0.6 on 2026-06-17 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_alter_providerprofile_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providerprofile',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=2),
        ),
    ]
