# Generated by Django 6.0.6 on 2026-06-20 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0011_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='title',
            field=models.CharField(default='New Notification', max_length=255),
        ),
    ]
