from django.urls import path
from .views import (CancelServiceRequestView, CustomerAllRequestsListView, CustomerProfileView, GetCurrentUserView, MarkNotificationsReadView, NotficationListView, NotificationUnreadCountView, ProfileView, ProviderDashboardView, ProviderListView, ProviderLocationUpdateView, ProviderProfileView, ReviewListProviderView, ServiceCategoryListPublicView, ServiceCategoryListView, ServiceRequestListCreateView , 
                    RegistrationView , 
                    CustomerRegistrationView ,
                    ProviderRegistrationView,
                    TestAuth,
                    ServiceRequestCreateView,
                    ServiceRequestListView,
                    AcceptServiceRequestView,
                    CustomerServiceRequestListView,
                    ProviderAcceptedServiceRequestListView,
                    CompleteRequestView,CreateReviewView,CustomerReviewList,ProviderReviewList,
                    ProviderCompletedServiceView,
                    ProviderCompletedRequestsListView,
                    CustomerCompletedRequestsListView,
                    BookProviderView,
                    ProviderAllRequestsListView,
                    ProviderAnalyticsView,
                    ProviderProfileView,
                    CustomerProfileDataView
                    )



urlpatterns = [
    path('requests/' , ServiceRequestListCreateView.as_view()),
    path('register/' , RegistrationView.as_view()),
    path('customer-register/' , CustomerRegistrationView.as_view()),
    path('provider-register/' , ProviderRegistrationView.as_view()),
    path('test-auth/' , TestAuth.as_view()),
    path('service-requests/' , ServiceRequestCreateView.as_view()),
    path('provider/services/' , ServiceRequestListView.as_view()),
    path('requests/<int:request_id>/accept/' , AcceptServiceRequestView.as_view()),
    path('customer/requests/' , CustomerServiceRequestListView.as_view()),
    path('provider/accepted-requests/' , ProviderAcceptedServiceRequestListView.as_view()),
    path('requests/<int:request_id>/complete/' , CompleteRequestView.as_view()),
    path('create/review/' , CreateReviewView.as_view()),
    path('customer/reviews/' , CustomerReviewList.as_view()),
    path('provider/reviews/' , ProviderReviewList.as_view()),
    path('provider/completed-services/' , ProviderCompletedServiceView.as_view()),
    path('provider/dashboard/' , ProviderDashboardView.as_view()),
    path('provider/profile/' , ProviderProfileView.as_view()),
    path('service-categories/' , ServiceCategoryListView.as_view()),
    path('profile/' , ProfileView.as_view()),
    path('category-list/' , ServiceCategoryListPublicView.as_view()),
    path('service-requests/create/<int:category_id>/' , ServiceRequestCreateView.as_view()),
    path('provider/completed-requests/' , ProviderCompletedRequestsListView.as_view()),
    path('customer/completed-requests/' , CustomerCompletedRequestsListView.as_view()),
    path('customer/all-requests/' , CustomerAllRequestsListView.as_view()),
    path('cancel-request/<int:request_id>/', CancelServiceRequestView.as_view(), name='cancel-request'),
    path('customer/details/profile/', CustomerProfileView.as_view(), name='customer-profile'),
    path('customer/provider-list/', ProviderListView.as_view(), name="provider-list"),
    path('book-provider/<int:provider_id>/', BookProviderView.as_view(), name='book-provider'),
    path('provider/all-requests/', ProviderAllRequestsListView.as_view(), name='provider-all-requests'),
    path('provider/analytics/', ProviderAnalyticsView.as_view(), name='provider-analytics'),
    path('provider/reviews/page/', ReviewListProviderView.as_view(), name='provider-reviews-page'),
    path("provider/details/list/", ProviderProfileView.as_view(), name="provider-profile-list"),
    path('customer/profile/data/', CustomerProfileDataView.as_view(), name='customer-profile-data'),
    path('notifications/', NotficationListView.as_view(), name='notification-list'),
    path('notifications/unread-count/', NotificationUnreadCountView.as_view(), name='notification-unread-count'),
    path('current/user/', GetCurrentUserView.as_view(), name='current-user'),
    path('mark/notifications/read/', MarkNotificationsReadView.as_view(), name='mark-notifications-read'),
    path('provider/location/', ProviderLocationUpdateView.as_view(), name='provider-location-update'),
]